### PR TITLE
JYC Update KitQL

### PR DESCRIPTION
**Pull request by jycouet**
I had a quick look

- [x] against localhost (because the other one was called "readonlydemo")
- [ ] I remove img as the asset server has issues (I don't know why)
  - [ ] have to put it back
- [x] token is stored in the localstorage (item added are now working)
- [ ] On page navigate, I don't know why `GetActiveOrder` is reseted! :o 

Todo next:
- [ ] refactor routes / components

### CODE REVIEW

**Comment by spences10** [comment]
> * [x]  against localhost (because the other one was called "readonlydemo")
It should be fine on readonly, I think it's possible to write to it, no problem though 😊
> * [ ]  I remove img as the asset server has issues (I don't know why)
>   * [ ]  have to put it back
Yes I often have issues with this, removing Vednure and `npx @vendure/create vendure` again to recreate the assets.
> * [x]  token is stored in the localstorage (item added are now working)
So this is a token rather than a cookie? A bearer token will need to be generated for each user, right?
> * [ ]  On page navigate, I don't know why `GetActiveOrder` is reseted! :o
Me neither 🙃 I'm not aware it was doing that though
> Todo next:
> * [ ]  refactor routes / components
More than happy to sit in with you on this when you do it, if you have the time 😊

Thanks

**Comment by michaelbromley** [comment]
>It should be fine on readonly, 

Yeah the "readonly" part refers to the fact that people cannot log in to the admin area and change the products & collections etc. It is still writable in terms of creating orders, customer accounts etc.

> I remove img as the asset server has issues (I don't know why)

Not sure what issues you ran into - maybe I can help?

**Comment by jycouet** [comment]
Thx for the info @michaelbromley, so I put back the "readonly" endpoint where I can add to cart 👍
In the readonly version, I have no issues with images, they are served perfectly 👍

_When I ran against local, the asset part is not serving img, maybe URLs are a bit different? Maybe it's a config to setup? In the end, I don't need it as against readonly, it's working well 👌_

I fixed most of the things in the app @spences10 🎉

I just have one question @michaelbromley, 
On `addItemToOrder` the state of `Order` is: `AddingItems`
On `adjustOrderLine` the state of `Order` is: `AddingItems`
Is this on purpose? Would it be possible in the response to get the action done?

**Comment by michaelbromley** [comment]
@jycouet ok good, glad the images are working on the remote server at least. Yeah might well be a local config issue that you ran into.

> On addItemToOrder the state of Order is: AddingItems
On adjustOrderLine the state of Order is: AddingItems
Is this on purpose? Would it be possible in the response to get the action done?

The `state` refers to the order's state machine state: https://www.vendure.io/docs/storefront/order-workflow/#order-state
So it will always be `AddingItems` until you come to check out, at which point it gets transitioned to `ArrangingPayment`.

There's no way to show the action done in the response, other than the fact that the mutation name is the top-level property of the response object.

**Comment by jycouet** [comment]
Okay @michaelbromley thx for the link 👍

Another question, when I pull the graphql schema, I see the node interface: 
```graphql
interface Node {
        id: ID!
}
```
But it's missing something like:
```graphql
extend type Query {
        node(id: ID!): Node
}
```
This makes an invalid schema.
Could you not implement Node? or make a Node resolver? 
Let me know

---

I believe that it's working now @spences10 🎉
You want to have a look?

**Comment by michaelbromley** [comment]
Well TIL about the top-level `node()` query!

So in Vendure, it is possible to use either integer IDs or UUIDs. When using integer IDs this would make a top-level node query impossible, since there are many entities which implement `Node` and have ID `1`.

What would you use the node query for?

**Comment by jycouet** [comment]
Well, in the example here, I don't use it.
But, we are checking the schema validity _(for advance pagination for example)_, and today it's complaining that the schema is not fully correct. (So I tricked the system to make it happy 😉)

I report you this, as some others could hit the same thing.
In the end, when discovering the schema, I see what possibilities are offered. 
And if a `type Xxx implements Node`, I should be able to use the `node` implem.

Let's turn it in the other way around; why do you specify `implements Node`?

**Comment by michaelbromley** [comment]
> Let's turn it in the other way around; why do you specify implements Node?

You know what, I'm not totally sure 😆 
I think maybe it was a case of "that seems to be the way it's done" when I was originally setting up the types, and I've never questioned it since. From reading more it seems to be a requirement for the Relay spec, but Vendure does not even try to conform to this spec (e.g. we do offset pagination) so it might well be that implementing Node is just cargo-culting in this case!

**Comment by jycouet** [comment]
> > Let's turn it in the other way around; why do you specify implements Node?
> 
> You know what, I'm not totally sure 😆 I think maybe it was a case of "that seems to be the way it's done" when I was originally setting up the types, and I've never questioned it since. From reading more it seems to be a requirement for the Relay spec, but Vendure does not even try to conform to this spec (e.g. we do offset pagination) so it might well be that implementing Node is just cargo-culting in this case!

😅

Easy then, remove all: `implements Node`, and done 🎉

**Comment by michaelbromley** [comment]
@jycouet from my side, I would be happy with that. It will also make it more discoverable for potential future collaborators. If Scott wants to do so I would grant you full write access.

**Comment by spences10** [comment]
> @jycouet from my side, I would be happy with that. It will also make it more discoverable for potential future collaborators. If Scott wants to do so I would grant you full write access.

Yep, I'm fine with that, it is for Vendure after all @michaelbromley 😊

@jycouet this is good to go now? I'll update the PR title if so, thanks 🙌

I'll take a look later, keen to understand how the cookies are working 🎉

**Comment by michaelbromley** [comment]
@spences10 cool, let's transfer it then! Because Vendure is an org, you can only transfer a repo to it if you have permissions to create repos for that org. If I recall correctly when we did something similar with the Remix starter, the easiest thing turned out to be to transfer it to my personal account (this one) and then from there I was able to transfer it to the Vendure org.

**Comment by jycouet** [comment]
Let's finalize tonight then transfer?
@spences10 we connect later? 😉

**Pull request merged**
